create table projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  image_url text,
  tech_stack text[],
  live_url text,
  status text default 'deployed'
);

create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text,
  status text default 'new'
);

create table finances (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null,
  amount numeric not null,
  description text,
  category text
);

create table certificates (
  id bigint generated by default as identity primary key,
  title text not null,
  issuer text not null,
  date_issued date,
  file_url text
);
