-- 1. Tabela de Certificados
CREATE TABLE IF NOT EXISTS public.certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

  title TEXT NOT NULL,         -- Nome do Curso/Certificado
  issuer TEXT NOT NULL,        -- Instituição (OneBitCode, Adobe, etc)
  issue_date DATE,             -- Data de emissão
  credential_url TEXT,         -- Link para validar (URL externa)
  image_url TEXT,              -- URL da imagem (Supabase Storage)

  skills TEXT[],               -- Array de tags ex: ['React', 'TS']
  is_featured BOOLEAN DEFAULT true -- Se deve aparecer em destaque
);

-- 2. Segurança (RLS)
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

-- Política 1: Qualquer um pode ler (Público) (incluindo usuários anônimos)
-- Nota: O supabase-js cliente anon usa a role 'anon' ou 'service_role'.
-- Para leitura publica no site, 'anon' e 'authenticated' (se houver login público futuro) devem ler.
-- Simplificando para 'true' cobre ambos, mas vamos ser específicos se precisar.
-- O comando do usuário pede "Qualquer um pode ler".
DROP POLICY IF EXISTS "Public view certificates" ON public.certificates;
CREATE POLICY "Public view certificates" ON public.certificates
  FOR SELECT USING (true);

-- Política 2: Apenas Admin pode criar/editar/deletar
-- O usuário forneceu "FOR ALL TO authenticated USING (true)".
-- Isso daria permissão para qualquer usuário logado.
-- Idealmente seria `USING (public.is_admin())` se tivermos essa função helper definida anteriormente (vimos ela no `002_admin_rls.sql`).
-- Vou manter a instrução do usuário mas adicionar o check de is_admin() se possível para manter consistência com as outras tabelas admin-only.
-- O prompt diz: "apenas admin autenticado".
-- Se eu usar apenas `TO authenticated`, qualquer um logado pode deletar.
-- Vou usar `public.is_admin()` se estiver disponível, mas o usuário forneceu o SQL explícito.
-- Vou usar o SQL fornecido pelo usuário para não desviar, mas ajustar o nome se necessário.
-- User SQL:
-- CREATE POLICY "Admin manages certificates" ON public.certificates
--   FOR ALL TO authenticated USING (true);
--
-- Vou melhorar para `USING (public.is_admin())` para segurança real, já que "authenticated" pode ser qualquer login no futuro.
-- Mas vou seguir o pedido do user para "apenas admin autenticado" que ele *implica* ser o authenticated do projeto dele (que é só admin).
-- Vou usar o SQL dele, mas talvez adicionar `WITH CHECK (auth.role() = 'authenticated')` é redundante com `TO authenticated`.

DROP POLICY IF EXISTS "Admin manages certificates" ON public.certificates;
CREATE POLICY "Admin manages certificates" ON public.certificates
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);
